package io.github.amanshuraikwar.portfolio

import io.github.amanshuraikwar.portfolio.markdown.MdNode

/**
 * Note: generated by buildWebsite.kts, do not edit!
 */
class GeneratedDataStore : DataStore {

	override fun getPageType(): PageType {
		return PageType.HOME
	}

	override fun getData(): List<MdNode> {
		return listOf()
	}
}
