name: Build Web HTML & JS Files

on:
  workflow_dispatch:
  pull_request:
    branches:
      - trunk

jobs:
  web-build-html-js:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Kotlin 1.6.0
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.0
          
      - name: Build Web HTML & JS Files
        run: |
          cd project-files/Portfolio
          kotlinc -script generateWebComposeMdLayouts.kts
