name: Deploy Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - trunk

permissions:
  contents: write

jobs:
  refresh-and-deploy:
    name: Refresh feeds and deploy Pages
    uses: ./.github/workflows/update-rss-feeds.yml
    secrets: inherit
