# # This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch:
  push:
    branches: [ trunk ]

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Set up Kotlin 1.6.0
        uses: fwilhe2/setup-kotlin@main
        with:
          version: 1.6.0
          
      - name: Build Web Resources
        run: |
          cd project-files/Portfolio
          kotlinc -script generateWebComposeMdLayouts.kts
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Upload artifacts
          path: docs
      
      - name: Download Artifacts
        uses: actions/download-artifact@v2
        with:
          path: docs

      - name: Display structure of Downloaded Diles
        run: ls -R
        working-directory: docs

      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          
